return {}

-- return {
--   "folke/noice.nvim",
--   opts = {
--     lsp = {
--       signature = {
--         enabled = true,
--         view = "hover",
--       },
--       hover = {
--         enabled = true,
--         view = "hover",
--       },
--     },
--     presets = {
--       bottom_search = true,
--       command_palette = true,
--     },
--   },
-- }
